logging:
    level:
        com: DEBUG

#mybatis:
#  mapperLocations: classpath*:mapper/*Mapper.xml
#  typeAliasesPackage: com.domain.model

spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/UserLogin?useUnicode=true&characterEncoding=UTF8&autoReconnect=true
      username: root
      password:
    redis:
      host: 127.0.0.1
      port: 6379